import type { Metadata } from 'next'
import { Header } from '@/components/Header'
import '@/styles/main.scss'
import { Chakra } from '@/components/Chakra'
import Footer from '@/components/Footer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Chakra>{children}</Chakra>
        <Footer />
      </body>
    </html>
  )
}
